name: "Import Resource Group State"

on:
  workflow_dispatch

jobs:
  terraform:
    name: Import Terraform State
    runs-on: ubuntu-latest

    env:

      # Used by Terraform for Service Principal authentication
      ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      # Used locally below
      CODE_PATH: "./terraform"

    steps:
      # Download the code from the repo
      - name: Checkout
        uses: actions/checkout@v2

      # Log into Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Terraform Setup
      - uses: hashicorp/setup-terraform@v1

      # Terraform Init
      - name: Terraform Init
        working-directory: ${{ env.CODE_PATH }}
        run: |
          terraform init \
            -backend-config="storage_account_name=${{ secrets.TF_STATE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER }}" \
            -backend-config="access_key=${{ secrets.TF_STATE_SECRET }}" \
            -backend-config="key=${{ secrets.PARAM_BASE_NAME }}.tfstate"

      # Terraform Import
      - name: Terraform Import
        working-directory: ${{ env.CODE_PATH }}
        env:
          TF_VAR_base_name: ${{ secrets.PARAM_BASE_NAME }}
          TF_VAR_location: ${{ secrets.PARAM_LOCATION }}
          TF_VAR_root_dns_name: ${{ secrets.PARAM_ROOT_DNS_NAME }}
          TF_VAR_contact_name: ${{ secrets.PARAM_CONTACT_NAME }}
          TF_VAR_contact_email: ${{ secrets.PARAM_CONTACT_EMAIL }}
        run: 
          terraform import azurerm_resource_group.rg /subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/$TF_VAR_base_name